version: "3"
services:
  nominatim:
    container_name: nominatim
    image: mediagis/nominatim:4.0
    restart: always
    ports:
        - "8080:8080"
    environment:
            # see https://github.com/mediagis/nominatim-docker/tree/master/3.7#configuration for more options
#          PBF_URL: https://download.geofabrik.de/europe/monaco-latest.osm.pbf
#          REPLICATION_URL: https://download.geofabrik.de/europe/monaco-updates/
         PBF_URL: https://download.geofabrik.de/europe/belgium-latest.osm.pbf
         REPLICATION_URL: https://download.geofabrik.de/europe/belgium-updates/
         NOMINATIM_PASSWORD: very_secure_password_1234 
         IMPORT_WIKIPEDIA: "true"
         IMPORT_STYLE: address
    volumes:
         - nominatim-data:/var/lib/postgresql/12/main
    shm_size: 1gb

    
  photon:
    build: 
        context: .
        dockerfile: Docker/Dockerfile_photon
        args: 
           - photon_data=Docker/photon.tar.gz
        # network: host
    ports:
      - "2322:2322"
      
  libpostal:
    build: 
        context: .
        dockerfile: Docker/Dockerfile_libpostal
        # network: host 
    ports:
            - "7000:7000"
    environment: 
      - NB_LPOST_WORKERS:1

  wrapper:
    build: 
        context: .
        dockerfile: Docker/Dockerfile_wrapper
        # network: host 
    ports:
      - "5000:5000"
    environment:
      - NB_WORKERS:4
      - PHOTON_HOST=photon:2322
      - LPOST_HOST=libpostal:7000
      - OSM_HOST=nominatim:8080
      - LOG_LEVEL=medium
#       - TRANSFORMERS=[ ["orig"],
#                           ["regex[init]"],
#                           ["nonum"],
#                           ["libpostal", "regex[lpost]"], 
#                           ["libpostal", "regex[lpost]", "nonum"], 
#                           ["libpostal", "regex[lpost]", "photon"], 
#                           ["libpostal", "regex[lpost]", "photon", "nonum"], 
#                           ["photon"],
#                           ["photon", "nonum"],
#                           ["libpostal", "nostreet"], 
#                           ["nostreet"]
#                         ]

volumes:
    nominatim-data:
    