version: "3"
services:
  photon:
    build: 
        context: .
        dockerfile: Docker/Dockerfile_photon
        args: 
           - photon_data=Docker/photon.tar.gz
        # network: host
    ports:
      - "2322:2322"
      
  libpostal:
    build: 
        context: .
        dockerfile: Docker/Dockerfile_libpostal
        # network: host 
    ports:
            - "7000:7000"
    environment: 
      - NB_LPOST_WORKERS:1

  wrapper:
    build: 
        context: .
        dockerfile: Docker/Dockerfile_wrapper
        # network: host 
    ports:
      - "5000:5000"
    environment:
      - NB_WORKERS=1
      - PHOTON_HOST=photon:2322
      - LPOST_HOST=libpostal:7000
      - OSM_HOST=10.1.0.45:8080 #172.17.0.2:8080 #172.17.0.2:8080  #10.1.0.45:7070
      - LOG_LEVEL=medium
      - TIMING=no
      - FASTMODE=yes

#       - TRANSFORMERS=[ ["orig"],
#                           ["regex[init]"],
#                           ["nonum"],
#                           ["libpostal", "regex[lpost]"], 
#                           ["libpostal", "regex[lpost]", "nonum"], 
#                           ["libpostal", "regex[lpost]", "photon"], 
#                           ["libpostal", "regex[lpost]", "photon", "nonum"], 
#                           ["photon"],
#                           ["photon", "nonum"],
#                           ["libpostal", "nostreet"], 
#                           ["nostreet"]
#                         ]
      
