openapi: '3.0.1'
info:
  title: Nominatim Wrapper
  version: '1.0.0'
servers:
  - url: "http://[docker ip]:5000"

paths:
  /search/?:
      post:
        parameters:
          - name: city
            in: query
            schema:
              type: string
          - name: housenumber
            in: query
            schema: 
              type: number
          - name: country
            in: query
            schema: 
              type: string
          - name: postcode
            in: query
            schema: 
              type: number
          - name: street
            in: query
            schema: 
              type: string
          
        responses:
          "200":
            description: Ok
            content:
              application/json:
                schema: 
                  type: object
                  properties:
                    match:
                      type: array
                      items:
                        $ref: '#/components/schemas/address'
                    rejected:
                      type: array
                      items:
                        $ref: '#/components/schemas/address'

  /batch/:
      post:
        requestBody:
          content:
            multipart/form-data:
              schema:
                type: object
                properties: 
                  media:
                    type: string
                    format: binary
                    title: addresses.csv
                    description: "csv file containing the addresses to geocode."
          
        responses:
          "200":
            description: Ok
            content:
              application/json:
                schema: 
                  type: array
                  items:
                    $ref: '#/components/schemas/batch_address'
components:
  schemas:
    batch_address:
      type: object
      description: Address returned with a batch call
      properties:
        "addr_key":
          type: number
          example: 1
        "lat":
          type: number
          example: 50.8161217
        "lon":
          type: number
          example: 4.4313059
        "place_rank":
          type: number
          example: 30
        "method":
          type: string
          example: "orig"
        "place_id":
          type: number
          example: 139737
        "addr_out_street": 
          type: string
          example: "Chaussée de Tervueren - Tervuursesteenweg"
        addr_out_number:
          type: number
          example: 10
        "in_house_nbr":
          type: number
          example: 10
        "lpost_house_nbr":
          type: number
          example: 10
        "lpost_unit":
          type: string
          example: ""
        "addr_out_postcode":
          type: number
          example: 1160
        "addr_out_city":
          type: string
          example: "Auderghem - Oudergem"
        "addr_out_country": 
          type: string
          example: "België / Belgique / Belgien"
        
    address: 
      type: object
      description: Representation of an address
      properties:
        SIM_city:
          type: number
          example: 0.44999999999999996
        SIM_house_nbr:
          type: number
          example: 1
        SIM_street:
          type: number
          example: 1
        SIM_street_which:
          type: string
          example: "addr_out_street"
        SIM_zip:
          type: number
          example: 1
        addr_out_city:
          type: string
          example: "Auderghem - Oudergem"
        addr_out_country:
          type: string
          example: "België / Belgique / Belgien"
        addr_out_number:
          type: number
          example: "12"
        addr_out_postcode:
          type: number
          example: "1160"
        addr_out_street:
          type: string
          example: "Chaussée de Tervueren - Tervuursesteenweg"
        display_name:
          type: string
          example: "12, Chaussée de Tervueren - Tervuursesteenweg, Cité Van Lindt, Auderghem - Oudergem, Brussel-Hoofdstad - Bruxelles-Capitale, Région de Bruxelles-Capitale - Brussels Hoofdstedelijk Gewest, 1160, België / Belgique / Belgien"
        in_house_nbr:
          type: number
          example: "12"
        lat:
          type: number
          example: "50.8161273"
        lon:
          type: number
          example: "4.4313582"
        lpost_house_nbr:
          type: number
          example: "12"
        lpost_unit:
          type: string
          example: ""
        method:
          type: string
          example: "orig"
        osm_addr_in:
          type: string
          example: "chaussee de tervuren, 12, 1160 Auderghem, "
        place_id:
          type: number
          example: 140731
        place_rank:
          type: number
          example: 30