FROM alpine:3.7

RUN apk --update add python3 python3-dev git gcc bash


RUN pip3 install Flask gunicorn requests 

# Install libpostal
# https://github.com/openvenues/libpostal 
RUN apk --update add curl autoconf automake libtool pkgconfig make

RUN apk add libc-dev

RUN mkdir /libpostal_code
RUN mkdir /libpostal_datadir

WORKDIR /libpostal_code
RUN git clone https://github.com/openvenues/libpostal
WORKDIR libpostal

# cf https://github.com/openvenues/libpostal/issues/319
# RUN sed -i 's/ -P $NUM_WORKERS//' /libpostal_code/src/libpostal_data

RUN apk add findutils

RUN ./bootstrap.sh 
RUN ./configure --datadir=/libpostal_datadir
RUN make -j4
RUN make install
RUN ldconfig /usr/local/lib


# Pypostal : https://github.com/openvenues/pypostal
RUN pip3 install postal

RUN mkdir /NominatimWrapper
WORKDIR /NominatimWrapper
COPY LibpostalREST.py ./


COPY Docker/start.sh /start.sh
CMD ["/start.sh", "libpostal"]  


EXPOSE 8080
