FROM alpine:3.7
  
RUN echo "http://dl-8.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories
RUN apk --no-cache --update-cache add gcc gfortran python3 python3-dev py3-pip build-base wget freetype-dev libpng-dev openblas-dev libjpeg-turbo-dev bash
RUN ln -s /usr/include/locale.h /usr/include/xlocale.h

RUN pip3 install --upgrade pip

RUN pip3 install cython wheel

RUN pip3 install --no-cache-dir Flask gunicorn matplotlib requests dask dask[dataframe] toolz jellyfish tqdm fsspec IPython openpyxl==3.0.1 bokeh pandas numpy


RUN mkdir /NominatimWrapper

WORKDIR /NominatimWrapper

COPY *.py ./


ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

WORKDIR /

COPY Docker/start.sh /start.sh
CMD ["/start.sh", "wrapper"]
