#FROM centos:7

FROM redhat/ubi9

ARG photon_data

RUN yum -y update && yum -y install java-11-openjdk-devel wget yum-utils && package-cleanup --leaves --all

# Install Photon

RUN mkdir /photon
WORKDIR /photon
RUN wget --progress=dot:mega https://github.com/komoot/photon/releases/download/0.4.4/photon-0.4.4.jar
COPY ${photon_data} photon.tar.gz
RUN tar xzf photon.tar.gz
RUN rm photon.tar.gz

# To get the full datafile : 
# RUN wget -O - http://download1.graphhopper.com/public/photon-db-latest.tar.bz2 | pbzip2 -cd | tar x


COPY Docker/start.sh /start.sh
CMD ["/start.sh", "photon"]

EXPOSE 2322
