FROM centos:7

ARG photon_data

RUN yum -y update

# Install Python & Packages
RUN yum -y install java wget

# Install Photon
# TODO : try photo 0.3.2

RUN mkdir /photon
WORKDIR /photon
RUN wget --progress=dot:mega https://github.com/komoot/photon/releases/download/0.3.1/photon-0.3.1.jar
COPY ${photon_data} photon.tar.gz
RUN tar xzf photon.tar.gz

# To get the full datafile : 
# RUN wget -O - http://download1.graphhopper.com/public/photon-db-latest.tar.bz2 | pbzip2 -cd | tar x


COPY Docker/start.sh /start.sh
CMD ["/start.sh", "photon"]

EXPOSE 2322
