#FROM centos:7

# Install Python & Packages


#FROM centos/python-38-centos7

#FROM python:3.8

FROM redhat/ubi9

USER root

RUN yum -y install python39 python3-wheel python3-pip python3-devel


RUN yum -y install autoconf-2.69 automake-1.16.2  libtool-2.4.6 pkgconfig make-4.3 yum-utils git && package-cleanup --leaves --all


# Install libpostal
# https://github.com/openvenues/libpostal 

RUN mkdir /libpostal_code
RUN mkdir /libpostal_datadir

WORKDIR /libpostal_code
RUN git clone https://github.com/openvenues/libpostal
WORKDIR libpostal

RUN ./bootstrap.sh 
RUN ./configure --datadir=/libpostal_datadir
RUN make -j4
RUN make install
RUN ldconfig /usr/local/lib


# Pypostal : https://github.com/openvenues/pypostal
RUN pip install Flask==2.2.5 gunicorn==22.0.0 requests==2.32.3
RUN pip install postal

RUN mkdir /NominatimWrapper
WORKDIR /NominatimWrapper

COPY libpostal_rest.py ./


COPY Docker/start.sh /start.sh
CMD ["/start.sh", "libpostal"]  


EXPOSE 8080
