#FROM centos:8

# Install Python & Packages

FROM centos/python-38-centos7

COPY Docker/requirements.txt ./
RUN pip3 install  -r requirements.txt

#

RUN mkdir NominatimWrapper
WORKDIR NominatimWrapper

ENV LANG en_US.UTF-8  
ENV LANGUAGE en_US:en  
ENV LC_ALL en_US.UTF-8     



COPY Docker/start.sh /start.sh
# Install code
COPY *.py ./

CMD ["/start.sh", "wrapper"]

EXPOSE 5000
